;;; cs-custom-set-test.el --- Tests for Custom set

;;; Commentary:

;;; Code:
(load-file "cs-custom-set.el")

(ert-deftest test-empty ()
  (should (cs:empty? (cs:custom-set '())))
  )

(ert-deftest test-not-empty ()
  (should (not (cs:empty? (cs:custom-set '(1)))))
  )

(ert-deftest test-cons-set ()
  (should (cs:equal? '(:set (9 10 6 5 2 4 3 1))
                     (cs:custom-set '(1 3 4 2 3 2 5 1 2 4 6 10 9 10 4 2 6))))
  )

(ert-deftest test-set-equal-0 ()
  (should (cs:equal? '(:set ()) '(:set nil)))
  )

(ert-deftest test-set-equal-1 ()
  (should (cs:equal? '(:set (1)) '(:set (1))))
  )

(ert-deftest test-set-equal-3 ()
  (should (cs:equal? '(:set (1 2 3)) '(:set (2 3 1))))
  )

(ert-deftest test-set-equal-8 ()
  (should (cs:equal? '(:set (9 10 6 5 2 4 3 1)) '(:set (2 4 3 1 10 9 6 5))))
  )

(ert-deftest test-not-set-equal-3 ()
  (should (not (cs:equal? '(:set (1 2 3)) '(:set (2 4 1)))))
  )

(ert-deftest test-not-set-equal ()
  (should (not (cs:equal? '(:set (1 2 3)) '(:set (1 2 4 5)))))
  )

(ert-deftest test-subset-base-cases ()
  (and (should (cs:subset? (cs:custom-set '()) (cs:custom-set '())))
       (should (cs:subset? (cs:custom-set '()) (cs:custom-set '(1))))
       (should (cs:subset? (cs:custom-set '(2)) (cs:custom-set '(1 2 3))))
       (should (cs:subset? (cs:custom-set '(2 1 3)) (cs:custom-set '(1 2 3))))
       (should (not (cs:subset? (cs:custom-set '(2 3 1)) (cs:custom-set '(3 2)))))
       ))

(ert-deftest test-add-elt ()
  (and (should (cs:equal? (cs:custom-set '(1 2 3)) (cs:add 3 (cs:custom-set '(2 1 3)))))
       (should (cs:equal? (cs:custom-set '(1 2 3)) (cs:add 3 (cs:custom-set '(2 1)))))
       (should (cs:equal? (cs:custom-set '(1)) (cs:add 1 (cs:custom-set '(1)))))
       (should (cs:equal? (cs:custom-set '(1)) (cs:add 1 (cs:custom-set '()))))
       (should (cs:equal? (cs:custom-set '(1 2 nil)) (cs:add nil (cs:custom-set '(2 1)))))
       )
  )

(ert-deftest test-union ()
  (and (should (cs:equal? (cs:custom-set '(1 3 5 2 4 6 8))
                          (cs:union (cs:tag-set '(1 5 3)) (cs:tag-set '(2 4 3 5 6 8)))))
       (should (cs:equal? (cs:custom-set '(1 3 5 2 4 6 8))
                          (cs:union (cs:tag-set '(1 5 3 2 4)) (cs:tag-set '(2 4 6 8)))))
       (should (cs:equal? (cs:custom-set '(1 3 5 2 4 6 8))
                          (cs:union (cs:tag-set '(1 5 3)) (cs:tag-set '(2 4 6 8)))))
       (should (cs:equal? (cs:custom-set '(1 3 5 2 4 6 8))
                          (cs:union (cs:tag-set '(1 5 3 2 4)) (cs:tag-set '(2 4 3 5 6 8)))))
       (should (cs:equal? (cs:custom-set '(1 3 5 2))
                          (cs:union (cs:tag-set '(1 5 3 2)) (cs:tag-set '(2 5 1 3)))))
       (should (cs:equal? (cs:custom-set '(1 3 5 2))
                          (cs:union (cs:tag-set '(1 3 5 2)) (cs:tag-set '(1 3 5 2)))))
       (should (cs:equal? (cs:custom-set '(1 3 5 2))
                          (cs:union (cs:tag-set '()) (cs:tag-set '(2 5 1 3)))))
       (should (cs:equal? (cs:custom-set '(1 3 5 2))
                          (cs:union (cs:tag-set '(2 1 3 5)) (cs:tag-set '()))))
       (should (cs:equal? (cs:custom-set '(1 3 5 2))
                          (cs:union (cs:tag-set '(2 3 5 1)) (cs:tag-set '(2 3 1)))))
       )
  )

(ert-deftest test-intersect ()
  (and (should (cs:equal? (cs:tag-set '(3 5))
                          (cs:intersect (cs:tag-set '(1 5 3)) (cs:tag-set'(2 4 3 5 6 8)))))
       (should (cs:equal? (cs:tag-set '(2 4))
                          (cs:intersect (cs:tag-set '(1 5 3 2 4))  (cs:tag-set '(2 4 6 8)))))
       (should (cs:equal? (cs:tag-set '())
                          (cs:intersect (cs:tag-set '(1 5 3)) (cs:tag-set '(2 4 6 8)))))
       (should (cs:equal? (cs:tag-set '(3 5 2 4))
                          (cs:intersect (cs:tag-set '(1 5 3 2 4)) (cs:tag-set '(2 4 3 5 6 8)))))
       (should (cs:equal? (cs:tag-set '(1 3 5 2))
                          (cs:intersect (cs:tag-set '(1 5 3 2)) (cs:tag-set '(2 5 1 3)))))
       (should (cs:equal? (cs:tag-set '(1 3 5 2))
                          (cs:intersect (cs:tag-set '(1 3 5 2)) (cs:tag-set '(1 3 5 2)))))
       (should (cs:equal? (cs:tag-set '())
                          (cs:intersect (cs:tag-set '()) (cs:tag-set '(2 5 1 3)))))
       (should (cs:equal? (cs:tag-set '())
                          (cs:intersect (cs:tag-set '(2 1 3 5)) (cs:tag-set '()))))
       (should (cs:equal? (cs:tag-set '(1 3 2))
                          (cs:intersect (cs:tag-set '(2 3 5 1)) (cs:tag-set '(2 3 1)))))
       )
  )

(ert-deftest test-diff ()
  (and (should (cs:equal? (cs:tag-set '(1))
                          (cs:diff (cs:tag-set '(1 5 3)) (cs:tag-set '(2 4 3 5 6 8)))))
       (should (cs:equal? (cs:tag-set '(1 5 3))
                          (cs:diff (cs:tag-set '(1 5 3 2 4)) (cs:tag-set '(2 4 6 8)))))
       (should (cs:equal? (cs:tag-set '(1 5 3))
                          (cs:diff (cs:tag-set '(1 5 3)) (cs:tag-set '(2 4 6 8)))))
       (should (cs:equal? (cs:tag-set '(1))
                          (cs:diff (cs:tag-set '(1 5 3 2 4)) (cs:tag-set  '(2 4 3 5 6 8)))))
       (should (cs:equal? (cs:tag-set  '())
                          (cs:diff (cs:tag-set '(1 5 3 2)) (cs:tag-set '(2 5 1 3)))))
       (should (cs:equal? (cs:tag-set '())
                          (cs:diff (cs:tag-set '(1 3 5 2)) (cs:tag-set '(1 3 5 2)))))
       (should (cs:equal? (cs:tag-set '())
                          (cs:diff (cs:tag-set '()) (cs:tag-set '(2 5 1 3)))))
       (should (cs:equal? (cs:tag-set '(2 1 3 5))
                          (cs:diff (cs:tag-set '(2 1 3 5)) (cs:tag-set '()))))
       (should (cs:equal? (cs:tag-set '(5))
                          (cs:diff (cs:tag-set '(2 3 5 1)) (cs:tag-set '(2 3 1)))))
   )
  )

;; other test
(ert-deftest test-null-1 ()
  (should (cs:null? (cs:tag-set '())))
  )

(ert-deftest test-null-2 ()
  (should (cs:null? (cs:tag-set nil)))
  )

(ert-deftest test-not-null ()
  (should (not (cs:null? (cs:tag-set '(1 3 2)))))
  )

(ert-deftest test-cs:member-1 ()
  (should (cs:member? 1 (cs:tag-set '(2 3 4 1 5)))))

(ert-deftest test-cs:member-2 ()
  (should (not (cs:member? 1 (cs:tag-set '())))))

(ert-deftest test-cs:member-3 ()
  (should (not (cs:member? 1 (cs:tag-set '(a b c))))))

(provide 'cs-custom-set-test)
;; cs-custom-set-test.el ends here
